### ISSUE TITLE
Enquire now button: Should this link to Contact us page?  But as per the current design, this will open as pop up enquiry form.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Paradisepools#28]
Applicable to Enquire now button in the pre-footer section, product single and services page.
![image](https://cloud.githubusercontent.com/assets/11186313/11030568/d969b0a8-8709-11e5-9fe8-12625e5e36b1.png)

**Comment by roseliesromeo** [comment]
Has this been clarified? I need a response for this.

**Comment by ganesh-titan** [comment]
I have discussed with TL. This page has already enquire form on right sidebar so it won't make sense to display enquire form in popup in same page that's why I have redirected it to contact us page as per scope document.
