### ISSUE TITLE
Footer: Broken layout of the footer menu.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Paradisepools#68]
S4
![image](https://cloud.githubusercontent.com/assets/11186313/11054044/c7405b32-87a1-11e5-8a00-36ec219e6cc6.png)

**Comment by roseliesromeo** [comment]
Not fixed.
![image](https://cloud.githubusercontent.com/assets/11186313/11261237/88db3d4a-8ead-11e5-8884-6579a2e12230.png)

**Comment by roseliesromeo** [comment]
Not fixed.
![image](https://cloud.githubusercontent.com/assets/11186313/11332068/13876dae-91fd-11e5-959c-05ade4a9065d.png)

**Comment by ganesh-titan** [comment]
FYI : On our devices ( S4 and i-touch) Working fine, They are not breaking to next line, Pls Advice.

![pic4](https://cloud.githubusercontent.com/assets/13450883/11361109/ba579164-92b0-11e5-813c-17f9154ef977.jpg)
![pic1](https://cloud.githubusercontent.com/assets/13450883/11361110/ba599d56-92b0-11e5-8ebb-f7432afde07e.jpg)

**Comment by roseliesromeo** [comment]
I am referring to the footer menu. The screenshot you added is for a different bug.
![image](https://cloud.githubusercontent.com/assets/11186313/11362464/aa29f94e-92ce-11e5-8083-681dd065a1f2.png)
