### ISSUE TITLE
Admin - page: Should we need to set the Category page template to About us page?

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Paradisepools#7]
![image](https://cloud.githubusercontent.com/assets/11186313/11025534/1157fdf4-86d7-11e5-83df-df34fa566ce0.png)

**Comment by ganesh-titan** [comment]
FYI : If u add Categories to main-menu once see the screenshot below and also 
![screen shot 2015-11-18 at 09 45 11](https://cloud.githubusercontent.com/assets/13450883/11232586/dc1e4aca-8dda-11e5-9eda-99d750c6a592.png)

**Comment by roseliesromeo** [comment]
As you can see in my screenshot, SAPPHIRE POOLS is not a category, it is a page. Another thing, Sapphire Pools is supposed to be a category.  Currently, it can be viewed as a page and as category.
![image](https://cloud.githubusercontent.com/assets/11186313/11234258/ee13723e-8e00-11e5-97c9-f9720275e63e.png)

**Comment by roseliesromeo** [comment]
We'll just close this and mark as won't fix.  Issue arise when contents were modified by Carin.  Pages are being used instead of categories for now.
![image](https://cloud.githubusercontent.com/assets/11186313/11329422/a90863be-91d6-11e5-88f5-85361d7d0890.png)
