### ISSUE TITLE
Contact us: Phone and fax numbers breaks to the next line.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Paradisepools#83]
S4 (portrait)
![image](https://cloud.githubusercontent.com/assets/11186313/11260971/170d727a-8eab-11e5-9565-af1b0f2d950e.png)

**Comment by roseliesromeo** [comment]
Not fixed yet. Already cleared cache/data.
![image](https://cloud.githubusercontent.com/assets/11186313/11329596/113e9b86-91d9-11e5-85c2-851079e1f238.png)

**Comment by ganesh-titan** [comment]
FYI : On our devices9 ( S4 and i-touch)  Working fine,  They are not breaking to next line, Pls Advice.
![pic3](https://cloud.githubusercontent.com/assets/13450883/11361018/f7d1eb94-92af-11e5-83ba-483a7ac39079.jpg)
![pic2](https://cloud.githubusercontent.com/assets/13450883/11361019/f7d3e8b8-92af-11e5-8931-d7b1b99da44c.jpg)
